# Generated by Django 2.0.3 on 2018-06-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0034_auto_20180620_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetemplateset',
            options={'ordering': ['sort_weight', 'id']},
        ),
        migrations.AddField(
            model_name='servicetemplateset',
            name='sort_weight',
            field=models.IntegerField(default=0, verbose_name='Weight in API output; smallest go first'),
        ),
    ]
