# Generated by Django 2.0.3 on 2018-06-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20180615_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentstatushistory',
            old_name='moved_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='appointmentstatushistory',
            old_name='moved_by',
            new_name='updated_by',
        ),
    ]
